# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|


  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.synced_folder "./", "/home/vagrant/node-app"

  config.vm.provision "shell", path: "./provision.sh", privileged: false

  # define three machines
  config.vm.define "A" do |nodeAppA|
    nodeAppA.vm.hostname = "A"
  end

  config.vm.define "B" do |nodeAppB|
    nodeAppB.vm.hostname = "B"
  end

  config.vm.define "C" do |nodeAppC|
    nodeAppC.vm.hostname = "C"
  end
end
